### ISSUE TITLE
Archived messages option

### ISSUE THREAD

**Issue by Uzytkownik2** [Nullspeaker/ch.py#70]
It would be good to have possibility to read archived messages at the time of entry into a room. Now we can see these archived messages only when we enter same Chatango room in http version. So if it is possible to implement it in program it would be good idea to be able to set this option.

**Comment by piks** [comment]
can you elaborate on this? From what ive understood you want it to output the history upon joining?

**Comment by asl97** [comment]
`onHistoryMessage`

**Comment by Uzytkownik2** [comment]
`onHistoryMessage` works good so this issue can be closed.

**Comment by asl97** [comment]
it's not officially support on this ch.py.

if you know the command, you can probably just use `_sendCommand`.

**Comment by Uzytkownik2** [comment]
@asl97 where can I find official support?  `onHistoryMessage` haven't counter messages parameter so I'm asking about set it other way.

**Comment by asl97** [comment]
I forgot to mention about listening to a specific reply using the `onRaw` after sending the command.
and checking the `room._i_log` after receiving it.

It would probably be better to directly add support into the library then to try to monkey-patch it.
____
Afaik, the only python library that currently and officially support it is chlib.
Although it has it's own set of problem and seem to be abandon as well.

There might be a (full)* fork of the ch.py that support it but I highly doubt it

Ps: If you didn't know, this repo has pretty much been abandon.
\* An unlinked fork/clone, it's where people just download the whole repo and create a new repo with it instead of clicking the fork button.
